stages:
    - build
    - test
    - analyse
    - deploy

sonarqube-check:
  stage: analyse
  image:
    name: sonarsource/sonar-scanner-cli:latest
    entrypoint: [""]
  variables:
    SONAR_USER_HOME: "${CI_PROJECT_DIR}/.sonar"
    GIT_DEPTH: "0"
  cache:
    key: "${CI_JOB_NAME}"
    paths:
      - .sonar/cache
  script:
    - sonar-scanner
  allow_failure: true
  only:
    - merge_requests
    - master # or the name of your main branch
    - develop
variables:
    PIP_DIR: "/root/.pip"
    PIP_FILE: "/root/.pip/pip.conf"

.before_script_template:
  before_script:
    - echo "Initialize environment"
    - apt-get update -qy
    - apt-get install -y python3-sphinx
    - 'mkdir $PIP_DIR'
    - 'touch $PIP_FILE'
    - 'echo [global] >> $PIP_FILE'
    - 'echo index-url = http://$DEVPI_HOST:3141/$DEVPI_INDEX/+simple/ >> $PIP_FILE'
    - 'echo [search] >> $PIP_FILE'
    - 'echo index = http://$DEVPI_HOST:3141/$DEVPI_INDEX/ >> $PIP_FILE'
    - 'echo [install] >> $PIP_FILE'
    - 'echo trusted-host = $DEVPI_HOST >> $PIP_FILE'
    - python -m pip install --upgrade pip
    - pip install -r requirements.txt

builds:
    extends: .before_script_template
    stage: build
    image: python:3.8
    script:
    - echo "Generate package and sphinx documentation"
    - python setup.py bdist_wheel build_sphinx

tests:
    extends: .before_script_template
    stage: test
    image: python:3.8
    script:
    - export PYTHONPATH="$PWD"
    - bash -c "coverage run -m unittest discover
    - bash -c "python -m coverage report"
    - bash -c "python -m coverage xml"
    coverage: '/TOTAL.*\s+(\d+\%)/'
    artifacts:
      reports:
        coverage_report:
          coverage_format: cobertura
          path: coverage.xml

production:
    extends: .before_script_template
    stage: deploy
    image: python:3.8
    script:
    - echo "publish revision"
    - export PYTHONPATH="$PWD"
    - bash -c "devpi use http://$DEVPI_HOST:3141/$DEVPI_INDEX"
    - bash -c "devpi login $DEVPI_LOGIN --password=$DEVPI_PASSWORD"
    - bash -c "devpi upload --format bdist_wheel --with-doc"

    only:
    - tags
