default:
    image: python:3.6

    before_script:
        - echo "Initialize environment"
        - apt-get update -qy
        - apt-get install -y python3-sphinx
        - pip install -r requirements.txt
stages:
    - build
    - test

doc:
    stage: build
    script:
    - echo "Generate sphinx documentation"
    - cd ./docs
    - make html
    - cd ../

tests:
    stage: test
    script:
    - export PYTHONPATH="$PWD"
    - bash -c "python -m coverage run ./tests/test.py"
    - bash -c "python -m coverage report"

production:
    stage: publish
    script:
    - echo "publish phase"
    - python setup.py sdist bdist_wheel
    - TWINE_PASSWORD=${DEPLOY_TOKEN_PASSWORD} TWINE_USERNAME=${DEPLOY_TOKEN_USERNAME}-deploy-token python -m twine upload --repository-url https://git.ul-ts.com/api/v4/projects/${CI_PROJECT_ID}/packages/pypi dist/*
    only:
        - tags
