import numpy as np
from pyhexdata.HexData import HexData

if __name__ == "__main__":
    print("Test np.array =>")
    value = np.array([0, 17, 53, 189, 207])
    HD = HexData(value=value)
    print(HD.to_string())
    print(HD.to_string(spaces=False))
    print(HD.to_bytes())
    print(HD.to_number())
    print("")

    print("Test bytearray =>")
    value = b'\x115\xbd\xcf'
    HD = HexData(value=value)
    print(HD.to_string())
    print(HD.to_string(spaces=False))
    print(HD.to_bytes())
    print(HD.to_number())
    print("")

    print("Test string with spaces =>")
    HD = HexData(value="11 35 BD CF")
    print(HD.to_string())
    print(HD.to_string(spaces=False))
    print(HD.to_bytes())
    print(HD.to_number())
    print("Test string without spaces =>")
    HD = HexData(value="1135BDCF")
    print(HD.to_string())
    print(HD.to_string(spaces=False))
    print(HD.to_bytes())
    print(HD.to_number())
    print("")

    print("Test int =>")
    HD = HexData(value=288734671)
    print(HD.to_string())
    print(HD.to_string(spaces=False))
    print(HD.to_bytes())
    print(HD.to_number())
    print("")

    print("Padding greater =>")
    HD.padding(6)
    print(HD.to_string())
    print(HD.to_string(spaces=False))
    print(HD.to_bytes())
    print(HD.to_number())
    print("Padding shorter =>")
    HD.padding(2)
    print(HD.to_string())
    print(HD.to_string(spaces=False))
    print(HD.to_bytes())
    print(HD.to_number())
    print("")

    print("Test rand without padding =>")
    HD = HexData.rand(4)
    print(HD.to_string())
    print(HD.to_string(spaces=False))
    print(HD.to_bytes())
    print(HD.to_number())
    print("")